# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web-server" do | vm1 |
    vm1.vm.box = "ubuntu/trusty64"
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.synced_folder "code/", "/var/www/html"

    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "web-server"
      vb.gui = true
      vb.memory = "512"
    end
    vm1.vm.provision "shell", path: "provision/web.sh"
  end
  config.vm.define "mysql-server" do | vm2 |
    vm2.vm.box = "ubuntu/trusty64"
    vm2.vm.network "private_network", ip: "192.168.33.20"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "mysql-server"
      vb.gui = true
      vb.memory = "512"
    end
    vm2.vm.provision "shell", path: "provision/mysql.sh"
  end
end
