node {

    docker.withServer('tcp://192.168.1.10:2376') {
        docker.image('lamp_mariadb').withRun('-p 3306:3306 --name mariadbj -v jenkins_mariadb_init:/docker-entrypoint-initdb.d/ --network="lampn"') {
            docker.image('lamp_php').withRun('-p 9000:9000 --name phpj -v jenkins_html:/var/www/html/ --entrypoint="docker-php-ext-install mysqli" --network="lampn"') {
                docker.image('lamp_apache').withRun('-p 80:80 \
                    -v jenkins_html:/var/www/html/ \
                    -v ${PWD}/apache_conf/demo-lamp.conf:/usr/local/apache2/conf/demo-lamp.conf \
                    -v ${PWD}/apache_conf/my-httpd.conf:/usr/local/apache2/conf/httpd.conf \
                    --network="lampn"') {
                    sleep("100")
                    sh "curl -i http://192.168.1.10:80/"
                    sh "curl -i http://192.168.1.10:80/index.php"
                    sh "curl -i http://192.168.1.10:80/dbtest.php"
                }
            }
        }
    }
}
