Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "docker" do |d|
    d.pull_images "rdev7/mysql"
    d.run "mysql", 
    	image: "rdev7/mysql",
    	args: "-p 3306:3306",
    	args: "-e MYSQL_ROOT_PASSWORD=root"
  end

  config.vm.provision "docker" do |d|
    d.pull_images "rdev7/php"
    d.run "php", 
    	image: "rdev7/php",
      args: %W[
        -p 9000:9000
        -v /vagrant/src/:/var/www/html
      ].join(' ')
  end

  config.vm.provision "docker" do |d|
    d.pull_images "rdev7/apache"
    d.run "apache", 
      image: "rdev7/apache",
      args: %W[
        -p 8080:80
        -v /vagrant/httpd.conf:/usr/local/apache2/conf/httpd.conf
        -v /vagrant/src/:/var/www/html
      ].join(' ')

  end

end