Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provision "docker" do |d|
    d.pull_images "tacis/ccdo_lamp_mariadb"
    d.run "mariadb", 
    	image: "tacis/ccdo_lamp_mariadb",
    	args: "-p 3306:3306"
  end
  
  config.vm.provision "docker" do |d|
    d.pull_images "tacis/ccdo_lamp_php"
    d.run "php", 
    	image: "tacis/ccdo_lamp_php",
    	args: "-p 9000:9000"
    
  end
  
  config.vm.provision "docker" do |d|
    d.pull_images "tacis/ccdo_lamp_apache"
    d.run "apache", 
    	image: "tacis/ccdo_lamp_apache",
    	args: "-p 80:80"
  end

  config.vm.network :forwarded_port,
    guest: 80, host: 50080

end

