pipeline {
  environment {
    nginx_imagename = "okachynskyi/crush:nginx"
    //php_imagename = "okachynskyi/crush:php"
    //mysql_imagename = "okachynskyi/crush:mysql"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git([url: 'https://github.com/bright-sudo/crash.git', branch: 'master', credentialsId: 'github'])
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build(nginx_imagename, "-f jenkins/Dockerfile .")
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            //dockerImage.push("$BUILD_NUMBER")
            dockerImage.push("nginx")
          }
        }
      }
    }
  }
}